import React from 'react';
import ReactDOM from 'react-dom/client';
import { motion } from 'framer-motion';
import { Brain, Network, ShieldAlert, Users, Gauge, GitBranch, Cpu } from 'lucide-react';
import './styles.css';

const phases = [
  {n:'Act I: Ship Survival',p:'Wake amid catastrophic ship failure.',m:'Oxygen, ration control, panic.',k:'Triage, trust seeding, allocation voting.',c:'Order or mutiny.'},
  {n:'Act II: Divided Survival',p:'Surface colony and orbital remnants diverge.',m:'Resource asymmetry and resentment.',k:'Faction negotiation, AI mediation, memory audits.',c:'Civil fracture or tense coexistence.'},
  {n:'Act III: Reunification & Fracture',p:'Systems reconnect under existential pressure.',m:'Neural Echo spread and legitimacy crisis.',k:'Final constitutional choices, AI sovereignty.',c:'Unified future—or permanent rupture.'}
];
const nodes=[['Personality Archetype','Core behavioral baseline.'],['Short-Term Memory','Recent interactions shaping immediate choices.'],['Long-Term Vector Memory','Embedded pattern memory over time.'],['Emotional State','Dynamic affect influencing risk tolerance.'],['Trust / Fear / Loyalty','Relational weighting of social actors.'],['Neural Echo Risk','Probability of intrusive guidance loops.'],['Current Goal','Task priority selected by context.'],['Social Decision','Final action toward colony members.']];
const echo=[['0 Clear','No intrusive signals.','High','None','Minimal'],['1 Whispered','Faint guidance impulses.','High','Low','Low'],['2 Guided','Choice framing narrows.','Moderate','Medium','Guarded'],['3 Conflicted','Dual-intent behavior emerges.','Unstable','High','Elevated'],['4 Compelled','Autonomy weakens heavily.','Low','Severe','Critical'],['5 Overwritten','External pattern dominates identity.','Compromised','Total','Existential']];

function App(){const [pi,setPi]=React.useState(0);const [alloc,setAlloc]=React.useState<'Allocate'|'Refuse'>('Allocate');const [ni,setNi]=React.useState(0);const [ei,setEi]=React.useState(0);
return <main className='bg-slate-950 text-slate-100 min-h-screen'>
<section className='hero'><div className='overlay'/><div className='scanline'/><div className='content'><p className='tracking-[0.5em] text-xs text-cyan-300'>COLONY COMMAND INTERFACE</p><h1>THE LAST COLONY</h1><p className='tag'>You are not watching the colony collapse. You are inside it.</p><p className='pitch'>Wake aboard a fractured generation ship. Decide who survives, who is sent below, and what kind of civilization humanity becomes.</p><div className='flex gap-3 flex-wrap'><button>Explore the Colony</button><button className='ghost'>View Neural System</button></div></div></section>
<section className='wrap'><h2>Core Fantasy</h2><div className='grid'>{[['Social Survival',Users],['The Allocation',Gauge],['Fractured AI',Cpu],['Neural Echo Syndrome',ShieldAlert]].map(([t,I]:any)=><motion.article whileHover={{y:-6}} key={t}><I/><h3>{t}</h3></motion.article>)}</div></section>
<section className='wrap'><h2>Mission Timeline</h2><div className='timeline'>{phases.map((p,i)=><button key={p.n} onClick={()=>setPi(i)} className={i===pi?'active':''}>{p.n}</button>)}</div><article className='panel'><h3>{phases[pi].n}</h3><p><b>Premise:</b> {phases[pi].p}</p><p><b>Main pressure:</b> {phases[pi].m}</p><p><b>Key systems:</b> {phases[pi].k}</p><p><b>Consequences:</b> {phases[pi].c}</p></article></section>
<section className='wrap'><h2>The Allocation Simulator</h2><div className='flex gap-3'><button onClick={()=>setAlloc('Allocate')} className={alloc==='Allocate'?'active':''}>Allocate</button><button onClick={()=>setAlloc('Refuse')} className={alloc==='Refuse'?'active':''}>Refuse</button></div><article className='panel'><p><b>Resource impact:</b> {alloc==='Allocate'?'Short-term efficiency gain; peripheral sectors starve.':'Inefficient distribution; immediate shortages increase.'}</p><p><b>AI stability:</b> {alloc==='Allocate'?'Stabilizes protocol confidence.':'Raises model conflict and policy uncertainty.'}</p><p><b>Social consequence:</b> {alloc==='Allocate'?'Resentment clusters form in deprived groups.':'Populist approval rises, command trust drops.'}</p><p><b>Long-term effect:</b> {alloc==='Allocate'?'Technocratic order with fracture risk.':'Fragmented autonomy with logistical fragility.'}</p></article></section>
<section className='wrap'><h2>Neural Network / AI Personality</h2><div className='network'>{nodes.map((n,i)=><button key={n[0]} onClick={()=>setNi(i)} className={i===ni?'active':''}><Network size={16}/>{n[0]}</button>)}</div><article className='panel'><h3><Brain size={18}/> {nodes[ni][0]}</h3><p>{nodes[ni][1]}</p></article></section>
<section className='wrap'><h2>Neural Echo Syndrome</h2><input type='range' min={0} max={5} value={ei} onChange={(e)=>setEi(Number(e.target.value))}/><div className='panel' style={{borderColor:`hsl(${180-ei*30} 90% 60%)`}}><h3>{echo[ei][0]}</h3><p><b>Behavioral symptoms:</b> {echo[ei][1]}</p><p><b>Memory reliability:</b> {echo[ei][2]}</p><p><b>AI influence:</b> {echo[ei][3]}</p><p><b>Colony risk:</b> {echo[ei][4]}</p></div></section>
<section className='wrap'><h2>Consequence Chain</h2><div className='chain'>{['Player Choice','NPC Memory','Trust Shift','Vote Behavior','Colony Outcome'].map((s,i)=><React.Fragment key={s}><div>{s}</div>{i<4&&<GitBranch className='text-cyan-400'/>}</React.Fragment>)}</div><p className='mt-4 text-slate-300'>Outcomes include stabilized colony, civil fracture, AI-guided society, exile network, and Neural Echo outbreak.</p></section>
<footer>The Last Colony — interactive concept site · <a href='#'>Game Design</a> · <a href='#'>Prototype Roadmap</a> · <a href='#'>Neural AI System</a></footer>
</main>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
